Make test-runner exit with non-zero status iff tests failed

diff --git a/tools/run-tests b/tools/run-tests
--- a/tools/run-tests
+++ b/tools/run-tests
@@ -95,3 +95,4 @@ if [[ ${#fails[@]} -gt 0 ]] ; then
 		echo "  ${name}"
 	done
 fi
+[[ ${#fails[@]} -eq 0 ]] || exit 1
